pipeline {
    environment {
      pod_automation_home = "${WORKSPACE}"
      aws_access_key = "$vi_access"
      aws_secret_key = "$vi_secret"
      }



    agent any
    parameters {
      choice choices: ['default', 'spinvm', 'baseImage', 'configuration'], description: '', name: 'Stage'
    }


    stages{

      stage('spinvm') {
        when {
            expression { params.Stage == "default" || params.Stage == "spinvm" }
           }
          steps {
      
            dir ('terraform/aws') {
            withEnv (["TF_VAR_aws_access_key=$vi_access", "TF_VAR_aws_secret_key=$vi_secret"]) {
             sh 'terraform init -plugin-dir=/usr/lib/terraform'
             sh 'terraform validate --var-file=environment/compute/amazonaws/com/variables.tfvars'
             sh 'terraform apply --auto-approve --var-file=environment/compute/amazonaws/com/variables.tfvars terraform/aws/main.tf --state=/aws/terraform.tfstate'
             sh "terraform output -state=/aws/app/terraform.tfstate host_ip | tr -d ',' > $pod_automation_home/ansible/hosts"
            }
           }
         }
      }
    }
}
