pipeline {
    environment {
      aws_username = "$vi_username"
      aws_password = "$vi_password"
    }



    agent any
    parameters {
      choice choices: ['default', 'spinvm', 'baseImage', 'configuration'], description: '', name: 'Stage'
    }


    stages{

      stage('spinvm') {
        when {
            expression { params.Stage == "default" || params.Stage == "spinvm" }
           }
          steps {
      
            dir ('terraform/aws') {
            withEnv (["TF_VAR_aws_username=$vi_username", "TF_VAR_aws_password=$vi_password"]) {
             sh 'terraform apply --var-file=environment/compute/amazonaws/com/variables.tfvars terraform/aws/main.tf --state /aws/app/terraform.tfstate'
             sh 'terraform output -state=/aws/app/terraform.tfstate ansible/hosts'
            }
           }
         }
      }
    }
}
